development:
  host: localhost
  database: rakuchan_development

test:
  host: localhost
  database: rakuchan_test

# set these environment variables on your prod server
production:
  host: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mongodb-2.0.1'].first['credentials']['hostname'] rescue 'localhost' %>
  port: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mongodb-2.0.1'].first['credentials']['port'] rescue 27017 %>
  database:  <%= JSON.parse( ENV['VCAP_SERVICES'] )['mongodb-2.0.1'].first['credentials']['db'] rescue 'cloud_foundry_mongodb_tutorial' %>
  username: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mongodb-2.0.1'].first['credentials']['username'] rescue '' %>
  password: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mongodb-2.0.1'].first['credentials']['password'] rescue '' %>

